const ARR_KEYS = [
    { eng: "`", class: "letters", code: "Backquote" },
    { key: "1", class: "number", code: "Digit1" },
    { key: "2", class: "number", code: "Digit2" },
    { key: "3", class: "number", code: "Digit3" },
    { key: "4", class: "number", code: "Digit4" },
    { key: "5", class: "number", code: "Digit5" },
    { key: "6", class: "number", code: "Digit6" },
    { key: "7", class: "number", code: "Digit7" },
    { key: "8", class: "number", code: "Digit8" },
    { key: "9", class: "number", code: "Digit9" },
    { key: "0", class: "number", code: "Digit0" },
    { eng: "-", class: "special", btn: "-", code: "Minus" },
    { eng: "=", class: "special", btn: "=", code: "Equal" },
    { eng: "Backspace", class: "special", btn: "Backspace", code: "Backspace" },
    { eng: "Tab", class: "special", btn: "Tab", code: "Tab" },
    { eng: "q", class: "letters", code: "KeyQ" },
    { eng: "w", class: "letters", code: "KeyW" },
    { eng: "e", class: "letters", code: "KeyE" },
    { eng: "r", class: "letters", code: "KeyR" },
    { eng: "t", class: "letters", code: "KeyT" },
    { eng: "y", class: "letters", code: "KeyY" },
    { eng: "u", class: "letters", code: "KeyU" },
    { eng: "i", class: "letters", code: "KeyI" },
    { eng: "o", class: "letters", code: "KeyO" },
    { eng: "p", class: "letters", code: "KeyP" },
    { key: "[", class: "special", btn: "[", code: "BracketLeft" },
    { key: "]", class: "special", btn: "]", code: "BracketRight" },
    { key: "\\", class: "special", btn: "\\", code: "Backslash" },
    { key: "CapsLock", class: "special", btn: "Caps Lock", code: "CapsLock" },
    { eng: "a", class: "letters", code: "KeyA" },
    { eng: "s", class: "letters", code: "KeyS" },
    { eng: "d", class: "letters", code: "KeyD" },
    { eng: "f", class: "letters", code: "KeyF" },
    { eng: "g", class: "letters", code: "KeyG" },
    { eng: "h", class: "letters", code: "KeyH" },
    { eng: "j", class: "letters", code: "KeyJ" },
    { eng: "k", class: "letters", code: "KeyK" },
    { eng: "l", class: "letters", code: "KeyL" },
    { key: ";", class: "special", btn: ";", code: "Semicolon" },
    { key: "'", class: "special", btn: "'", code: "Quote" },
    { key: "Enter", class: "special", btn: "Enter", code: "Enter" },
    { key: "Shift", class: "shift", btn: "Shift", code: "ShiftLeft" },
    { eng: "z", class: "letters", code: "KeyZ" },
    { eng: "x", class: "letters", code: "KeyX" },
    { eng: "c", class: "letters", code: "KeyC" },
    { eng: "v", class: "letters", code: "KeyV" },
    { eng: "b", class: "letters", code: "KeyB" },
    { eng: "n", class: "letters", code: "KeyN" },
    { eng: "m", class: "letters", code: "KeyM" },
    { key: ",", class: "special", btn: ",", code: "Comma" },
    { key: ".", class: "special", btn: ".", code: "Period" },
    { key: "Shift", class: "shift", btn: "Shift", code: "ShiftRight" },
    { key: "ArrowUp", class: "special", btn: "↑", code: "ArrowUp" },
    { key: "/", class: "special", btn: "/", code: "Slash" },
    { key: "Control", class: "special", btn: "Сtrl", code: "ControlLeft" },
    { key: "Meta", class: "special", btn: "Win", code: "MetaLeft" },
    { key: "Alt", class: "special", btn: "Alt", code: "AltLeft" },
    { key: " ", class: "space", code: "Space" },
    { key: "Alt", class: "special", btn: "Alt", code: "AltRight" },
    { key: "Control", class: "special", btn: "Сtrl", code: "ControlRight" },
    { key: "ArrowLeft", class: "special", btn: "←", code: "ArrowLeft" },
    { key: "ArrowDown", class: "special", btn: "↓", code: "ArrowDown" },
    { key: "ArrowRight", class: "special", btn: "→", code: "ArrowRight" },
];
export { ARR_KEYS };
