const ARR_KEYS = [
    {
        engText: "`",
        class: "symbol",
        code: "Backquote",
        uaText: "'",
        shiftEng: "~",
        shiftUA: "₴",
    },
    {
        engText: "1",
        class: "number",
        code: "Digit1",
        uaText: "1",
        shiftEng: "!",
        shiftUA: "!",
    },
    {
        engText: "2",
        class: "number",
        code: "Digit2",
        uaText: "2",
        shiftEng: "@",
        shiftUA: '"',
    },
    {
        engText: "3",
        class: "number",
        code: "Digit3",
        uaText: "3",
        shiftEng: "#",
        shiftUA: "№",
    },
    {
        engText: "4",
        class: "number",
        code: "Digit4",
        uaText: "4",
        shiftEng: "$",
        shiftUA: ";",
    },
    {
        engText: "5",
        class: "number",
        code: "Digit5",
        uaText: "5",
        shiftEng: "%",
        shiftUA: "%",
    },
    {
        engText: "6",
        class: "number",
        code: "Digit6",
        uaText: "6",
        shiftEng: "^",
        shiftUA: ":",
    },
    {
        engText: "7",
        class: "number",
        code: "Digit7",
        uaText: "7",
        shiftEng: "&",
        shiftUA: "?",
    },
    {
        engText: "8",
        class: "number",
        code: "Digit8",
        uaText: "8",
        shiftEng: "*",
        shiftUA: "*",
    },
    {
        engText: "9",
        class: "number",
        code: "Digit9",
        uaText: "9",
        shiftEng: "(",
        shiftUA: "(",
    },
    {
        engText: "0",
        class: "number",
        code: "Digit0",
        uaText: "0",
        shiftEng: ")",
        shiftUA: ")",
    },
    {
        engText: "-",
        class: "symbol",
        code: "Minus",
        uaText: "-",
        shiftEng: "_",
        shiftUA: "_",
    },
    {
        engText: "=",
        class: "symbol",
        code: "Equal",
        uaText: "=",
        shiftEng: "+",
        shiftUA: "+",
    },
    {
        engText: "Backspace",
        class: "special",
        code: "Backspace",
        uaText: "Backspace",
        shiftEng: "Backspace",
        shiftUA: "Backspace",
    },
    {
        engText: "Tab",
        class: "special",
        code: "Tab",
        uaText: "Tab",
        shiftEng: "Tab",
        shiftUA: "Tab",
    },
    {
        engText: "q",
        class: "letters",
        code: "KeyQ",
        uaText: "й",
        shiftEng: "Q",
    },
    {
        engText: "w",
        class: "letters",
        code: "KeyW",
        uaText: "ц",
        shiftEng: "W",
    },
    {
        engText: "e",
        class: "letters",
        code: "KeyE",
        uaText: "у",
        shiftEng: "E",
    },
    {
        engText: "r",
        class: "letters",
        code: "KeyR",
        uaText: "к",
        shiftEng: "R",
    },
    {
        engText: "t",
        class: "letters",
        code: "KeyT",
        uaText: "е",
        shiftEng: "T",
    },
    {
        engText: "y",
        class: "letters",
        code: "KeyY",
        uaText: "н",
        shiftEng: "Y",
    },
    {
        engText: "u",
        class: "letters",
        code: "KeyU",
        uaText: "г",
        shiftEng: "U",
    },
    {
        engText: "i",
        class: "letters",
        code: "KeyI",
        uaText: "ш",
        shiftEng: "I",
    },
    {
        engText: "o",
        class: "letters",
        code: "KeyO",
        uaText: "щ",
        shiftEng: "O",
    },
    {
        engText: "p",
        class: "letters",
        code: "KeyP",
        uaText: "з",
        shiftEng: "P",
    },
    {
        engText: "[",
        class: "symbol",
        code: "BracketLeft",
        uaText: "х",
        shiftEng: "{",
        shiftUA: "Х",
    },
    {
        engText: "]",
        class: "symbol",
        code: "BracketRight",
        uaText: "ї",
        shiftEng: "}",
        shiftUA: "Ї",
    },
    {
        engText: "\\",
        class: "symbol",
        code: "Backslash",
        uaText: "\\",
        shiftEng: "|",
        shiftUA: "/",
    },
    {
        engText: "Caps Lock",
        class: "special",
        code: "CapsLock",
        uaText: "Caps Lock",
        shiftEng: "Caps Lock",
        shiftUA: "Caps Lock",
    },
    {
        engText: "a",
        class: "letters",
        code: "KeyA",
        uaText: "ф",
        shiftEng: "A",
    },
    {
        engText: "s",
        class: "letters",
        code: "KeyS",
        uaText: "і",
        shiftEng: "S",
    },
    {
        engText: "d",
        class: "letters",
        code: "KeyD",
        uaText: "в",
        shiftEng: "D",
    },
    {
        engText: "f",
        class: "letters",
        code: "KeyF",
        uaText: "а",
        shiftEng: "F",
    },
    {
        engText: "g",
        class: "letters",
        code: "KeyG",
        uaText: "п",
        shiftEng: "G",
    },
    {
        engText: "h",
        class: "letters",
        code: "KeyH",
        uaText: "р",
        shiftEng: "H",
    },
    {
        engText: "j",
        class: "letters",
        code: "KeyJ",
        uaText: "о",
        shiftEng: "J",
    },
    {
        engText: "k",
        class: "letters",
        code: "KeyK",
        uaText: "л",
        shiftEng: "K",
    },
    {
        engText: "l",
        class: "letters",
        code: "KeyL",
        uaText: "д",
        shiftEng: "L",
    },
    {
        engText: ";",
        class: "symbol",
        code: "Semicolon",
        uaText: "ж",
        shiftEng: ":",
        shiftUA: "Ж",
    },
    {
        engText: "'",
        class: "symbol",
        code: "Quote",
        uaText: "є",
        shiftEng: '"',
        shiftUA: "Є",
    },
    {
        engText: "Enter",
        class: "special",
        code: "Enter",
        uaText: "Enter",
        shiftEng: "Enter",
        shiftUA: "Enter",
    },
    {
        engText: "Shift",
        class: "shift",
        code: "ShiftLeft",
        uaText: "Shift",
        shiftEng: "Shift",
        shiftUA: "Shift",
    },
    {
        engText: "z",
        class: "letters",
        code: "KeyZ",
        uaText: "я",
        shiftEng: "Z",
    },
    {
        engText: "x",
        class: "letters",
        code: "KeyX",
        uaText: "ч",
        shiftEng: "X",
    },
    {
        engText: "c",
        class: "letters",
        code: "KeyC",
        uaText: "с",
        shiftEng: "C",
    },
    {
        engText: "v",
        class: "letters",
        code: "KeyV",
        uaText: "м",
        shiftEng: "V",
    },
    {
        engText: "b",
        class: "letters",
        code: "KeyB",
        uaText: "и",
        shiftEng: "B",
    },
    {
        engText: "n",
        class: "letters",
        code: "KeyN",
        uaText: "т",
        shiftEng: "N",
    },
    {
        engText: "m",
        class: "letters",
        code: "KeyM",
        uaText: "ь",
        shiftEng: "M",
    },
    {
        engText: ",",
        class: "symbol",
        code: "Comma",
        uaText: "б",
        shiftEng: "<",
        shiftUA: "Б",
    },
    {
        engText: ".",
        class: "symbol",
        code: "Period",
        uaText: "ю",
        shiftEng: ">",
        shiftUA: "Ю",
    },
    {
        engText: "Shift",
        class: "shift",
        code: "ShiftRight",
        uaText: "Shift",
        shiftEng: "Shift",
        shiftUA: "Shift",
    },
    {
        engText: "↑",
        class: "symbol",
        code: "ArrowUp",
        uaText: "↑",
        shiftEng: "↑",
        shiftUA: "↑",
    },
    {
        engText: "/",
        class: "symbol",
        code: "Slash",
        uaText: ".",
        shiftEng: "?",
        shiftUA: ",",
    },
    {
        engText: "Сtrl",
        class: "special",
        code: "ControlLeft",
        uaText: "Сtrl",
        shiftEng: "Сtrl",
        shiftUA: "Сtrl",
    },
    {
        engText: "Win",
        class: "special",
        code: "MetaLeft",
        uaText: "Win",
        shiftEng: "Win",
        shiftUA: "Win",
    },
    {
        engText: "Alt",
        class: "special",
        code: "AltLeft",
        uaText: "Alt",
        shiftEng: "Alt",
        shiftUA: "Alt",
    },
    {
        engText: " ",
        class: "space",
        code: "Space",
        uaText: " ",
        shiftEng: " ",
        shiftUA: " ",
    },
    {
        engText: "Alt",
        class: "special",
        code: "AltRight",
        uaText: "Alt",
        shiftEng: "Alt",
        shiftUA: "Alt",
    },
    {
        engText: "Сtrl",
        class: "special",
        code: "ControlRight",
        uaText: "Сtrl",
        shiftEng: "Сtrl",
        shiftUA: "Сtrl",
    },
    {
        engText: "←",
        class: "symbol",
        code: "ArrowLeft",
        uaText: "←",
        shiftEng: "←",
        shiftUA: "←",
    },
    {
        engText: "↓",
        class: "symbol",
        code: "ArrowDown",
        uaText: "↓",
        shiftEng: "↓",
        shiftUA: "↓",
    },
    {
        engText: "→",
        class: "symbol",
        code: "ArrowRight",
        uaText: "→",
        shiftEng: "→",
        shiftUA: "→",
    },
];
export { ARR_KEYS };
